package code128

var encodingTable [107][]bool = [107][]bool{
	[]bool{true, true, false, true, true, false, false, true, true, false, false},
	[]bool{true, true, false, false, true, true, false, true, true, false, false},
	[]bool{true, true, false, false, true, true, false, false, true, true, false},
	[]bool{true, false, false, true, false, false, true, true, false, false, false},
	[]bool{true, false, false, true, false, false, false, true, true, false, false},
	[]bool{true, false, false, false, true, false, false, true, true, false, false},
	[]bool{true, false, false, true, true, false, false, true, false, false, false},
	[]bool{true, false, false, true, true, false, false, false, true, false, false},
	[]bool{true, false, false, false, true, true, false, false, true, false, false},
	[]bool{true, true, false, false, true, false, false, true, false, false, false},
	[]bool{true, true, false, false, true, false, false, false, true, false, false},
	[]bool{true, true, false, false, false, true, false, false, true, false, false},
	[]bool{true, false, true, true, false, false, true, true, true, false, false},
	[]bool{true, false, false, true, true, false, true, true, true, false, false},
	[]bool{true, false, false, true, true, false, false, true, true, true, false},
	[]bool{true, false, true, true, true, false, false, true, true, false, false},
	[]bool{true, false, false, true, true, true, false, true, true, false, false},
	[]bool{true, false, false, true, true, true, false, false, true, true, false},
	[]bool{true, true, false, false, true, true, true, false, false, true, false},
	[]bool{true, true, false, false, true, false, true, true, true, false, false},
	[]bool{true, true, false, false, true, false, false, true, true, true, false},
	[]bool{true, true, false, true, true, true, false, false, true, false, false},
	[]bool{true, true, false, false, true, true, true, false, true, false, false},
	[]bool{true, true, true, false, true, true, false, true, true, true, false},
	[]bool{true, true, true, false, true, false, false, true, true, false, false},
	[]bool{true, true, true, false, false, true, false, true, true, false, false},
	[]bool{true, true, true, false, false, true, false, false, true, true, false},
	[]bool{true, true, true, false, true, true, false, false, true, false, false},
	[]bool{true, true, true, false, false, true, true, false, true, false, false},
	[]bool{true, true, true, false, false, true, true, false, false, true, false},
	[]bool{true, true, false, true, true, false, true, true, false, false, false},
	[]bool{true, true, false, true, true, false, false, false, true, true, false},
	[]bool{true, true, false, false, false, true, true, false, true, true, false},
	[]bool{true, false, true, false, false, false, true, true, false, false, false},
	[]bool{true, false, false, false, true, false, true, true, false, false, false},
	[]bool{true, false, false, false, true, false, false, false, true, true, false},
	[]bool{true, false, true, true, false, false, false, true, false, false, false},
	[]bool{true, false, false, false, true, true, false, true, false, false, false},
	[]bool{true, false, false, false, true, true, false, false, false, true, false},
	[]bool{true, true, false, true, false, false, false, true, false, false, false},
	[]bool{true, true, false, false, false, true, false, true, false, false, false},
	[]bool{true, true, false, false, false, true, false, false, false, true, false},
	[]bool{true, false, true, true, false, true, true, true, false, false, false},
	[]bool{true, false, true, true, false, false, false, true, true, true, false},
	[]bool{true, false, false, false, true, true, false, true, true, true, false},
	[]bool{true, false, true, true, true, false, true, true, false, false, false},
	[]bool{true, false, true, true, true, false, false, false, true, true, false},
	[]bool{true, false, false, false, true, true, true, false, true, true, false},
	[]bool{true, true, true, false, true, true, true, false, true, true, false},
	[]bool{true, true, false, true, false, false, false, true, true, true, false},
	[]bool{true, true, false, false, false, true, false, true, true, true, false},
	[]bool{true, true, false, true, true, true, false, true, false, false, false},
	[]bool{true, true, false, true, true, true, false, false, false, true, false},
	[]bool{true, true, false, true, true, true, false, true, true, true, false},
	[]bool{true, true, true, false, true, false, true, true, false, false, false},
	[]bool{true, true, true, false, true, false, false, false, true, true, false},
	[]bool{true, true, true, false, false, false, true, false, true, true, false},
	[]bool{true, true, true, false, true, true, false, true, false, false, false},
	[]bool{true, true, true, false, true, true, false, false, false, true, false},
	[]bool{true, true, true, false, false, false, true, true, false, true, false},
	[]bool{true, true, true, false, true, true, true, true, false, true, false},
	[]bool{true, true, false, false, true, false, false, false, false, true, false},
	[]bool{true, true, true, true, false, false, false, true, false, true, false},
	[]bool{true, false, true, false, false, true, true, false, false, false, false},
	[]bool{true, false, true, false, false, false, false, true, true, false, false},
	[]bool{true, false, false, true, false, true, true, false, false, false, false},
	[]bool{true, false, false, true, false, false, false, false, true, true, false},
	[]bool{true, false, false, false, false, true, false, true, true, false, false},
	[]bool{true, false, false, false, false, true, false, false, true, true, false},
	[]bool{true, false, true, true, false, false, true, false, false, false, false},
	[]bool{true, false, true, true, false, false, false, false, true, false, false},
	[]bool{true, false, false, true, true, false, true, false, false, false, false},
	[]bool{true, false, false, true, true, false, false, false, false, true, false},
	[]bool{true, false, false, false, false, true, true, false, true, false, false},
	[]bool{true, false, false, false, false, true, true, false, false, true, false},
	[]bool{true, true, false, false, false, false, true, false, false, true, false},
	[]bool{true, true, false, false, true, false, true, false, false, false, false},
	[]bool{true, true, true, true, false, true, true, true, false, true, false},
	[]bool{true, true, false, false, false, false, true, false, true, false, false},
	[]bool{true, false, false, false, true, true, true, true, false, true, false},
	[]bool{true, false, true, false, false, true, true, true, true, false, false},
	[]bool{true, false, false, true, false, true, true, true, true, false, false},
	[]bool{true, false, false, true, false, false, true, true, true, true, false},
	[]bool{true, false, true, true, true, true, false, false, true, false, false},
	[]bool{true, false, false, true, true, true, true, false, true, false, false},
	[]bool{true, false, false, true, true, true, true, false, false, true, false},
	[]bool{true, true, true, true, false, true, false, false, true, false, false},
	[]bool{true, true, true, true, false, false, true, false, true, false, false},
	[]bool{true, true, true, true, false, false, true, false, false, true, false},
	[]bool{true, true, false, true, true, false, true, true, true, true, false},
	[]bool{true, true, false, true, true, true, true, false, true, true, false},
	[]bool{true, true, true, true, false, true, true, false, true, true, false},
	[]bool{true, false, true, false, true, true, true, true, false, false, false},
	[]bool{true, false, true, false, false, false, true, true, true, true, false},
	[]bool{true, false, false, false, true, false, true, true, true, true, false},
	[]bool{true, false, true, true, true, true, false, true, false, false, false},
	[]bool{true, false, true, true, true, true, false, false, false, true, false},
	[]bool{true, true, true, true, false, true, false, true, false, false, false},
	[]bool{true, true, true, true, false, true, false, false, false, true, false},
	[]bool{true, false, true, true, true, false, true, true, true, true, false},
	[]bool{true, false, true, true, true, true, false, true, true, true, false},
	[]bool{true, true, true, false, true, false, true, true, true, true, false},
	[]bool{true, true, true, true, false, true, false, true, true, true, false},
	[]bool{true, true, false, true, false, false, false, false, true, false, false},
	[]bool{true, true, false, true, false, false, true, false, false, false, false},
	[]bool{true, true, false, true, false, false, true, true, true, false, false},
	[]bool{true, true, false, false, false, true, true, true, false, true, false, true, true},
}

const startASymbol byte = 103
const startBSymbol byte = 104
const startCSymbol byte = 105
const stopSymbol byte = 106

const bTable = " !\"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdefghijklmnopqrstuvwxyz{|}~"
